export const NOTIFY_USER = "NOTIFY_USER";
// settings types
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
export const DISABLE_BALANCE_ON_ADD = "DISABLE_BALANCE_ON_ADD";
export const DISABLE_BALANCE_ON_EDIT = "DISABLE_BALANCE_ON_EDIT";
export const RESET_SETTINGS = "RESET_SETTINGS";
